# Generated by Django 2.0.13 on 2019-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default=0, upload_to='%Y/%m/%d/img'),
            preserve_default=False,
        ),
    ]
