# Generated by Django 2.0.13 on 2019-05-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
