# Generated by Django 2.0.13 on 2019-05-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190519_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='number',
            new_name='num',
        ),
    ]
