# Generated by Django 2.0.13 on 2019-05-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_category_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
