# Generated by Django 2.0.13 on 2019-05-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_category_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
